### ISSUE TITLE
SPF Loop Detection

### ISSUE THREAD

**Issue by membero** [asggo/spf#5]
Hello,

I am experiencing a problem with two domains referring each other. Situation:

domain1.tld IN TXT "v=spf1 include:domain2.tld ?all"
domain2.tld IN TXT "v=spf1 include:domain1.tld ?all"

At the moment I am helping me by adding an integer "counter" to the following methods:

Evaluate
SPFTest
Test

In Evaluate I have changed case include to:

case "include":
		email := "info@" + m.Domain
		if counter < 25 {
			counter++
			return SPFTest(client, email, counter)
		}
		return "", errors.New("SPF DNS Record seems to have a loop.")

I am not good at programming Golang, so this might not be an elegant way. If you wish I could make a PR, but I think you will have better ideas to solve this problem.

**Comment by orestonce** [comment]
I have same problem, when I SPFTest, it recursive forever:
````
spf.SPFTest(`1.1.1.1`, `admin@pchome.com.tw`)
````
These two domain names include each other: `epaper.com.tw <-> pchome.com.tw`
Acording to [this posts](https://help.returnpath.com/hc/en-us/articles/222479888-How-can-I-avoid-SPF-failures-if-I-am-reaching-the-DNS-lookup-limit-),dns lookup should be limited to 10.

**Comment by averagesecurityguy** [comment]
Thank you @membero for raising this issue and @orestonce for providing a test case. I am sorry it has taken me so long to get to this issue but I am working on a fix to address it and will let you know when it is committed.

**Comment by averagesecurityguy** [comment]
Addressed in commit 3e270ddb6136debe12000140229018aef1864d6e
