### ISSUE TITLE
SPFTest broken when record has multiple includes

### ISSUE THREAD

**Issue by jkirkwood** [asggo/spf#7]
I'm trying to validate IP addresses against Google's SPF record. Their top SPF record is on`_spf.google.com` which is set to:

```v=spf1 include:_netblocks.google.com include:_netblocks2.google.com include:_netblocks3.google.com ~all```

If I run `spf.SPFTest("35.190.247.0", "info@google.com")` (IP in _netblocks) the result is `Pass` as expected.

If I run `spf.SPFTest("172.217.0.0", "info@google.com")` (IP in _netblocks3) the result is `SoftFail`.

However if I run `spf.SPFTest("172.217.0.0", "info@_netblocks3.google.com")` the result is `Pass`.

It appears that all `include` fields are not being considered in the SPF record

**Comment by averagesecurityguy** [comment]
I'm working on a solution to this. When the IP is checked against the subdomain _netblocks.google.com it is getting a SoftFail for the _netblocks.google.com domain and is pushing that up as a SoftFail for the google.com domain. Sorry it took so long to get back to you.

**Comment by jkirkwood** [comment]
Thanks @averagesecurityguy. I figured it was something like that.

**Comment by averagesecurityguy** [comment]
I believe this is resolved now. Test case passes. Please let me know if there are any other issues.
